UpserveWifi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^honeypot/', include('honeypot.urls')),
    url(r'^admin/', admin.site.urls),
]

honeypot/urls.py
from django.conf.urls import url

from . import views

app_name = 'honeypot'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<store_id>[0-9]+)/$', views.welcome, name='welcome'),
	url(r'^(?P<store_id>[0-9]+)/thanks/$', views.thanks, name='thanks'),
]

honeypot/models.py
from django.db import models
from django.forms import ModelForm, TextInput

class WifiGuest(models.Model):
	last_name = models.CharField(max_length=200)
	first_name = models.CharField(max_length=200)
	email = models.CharField(max_length=300)
	def __str__(self):
		return self.email

class StoreInfo(models.Model):
	spu = models.CharField(max_length=200, blank=True)
	loyaltyurl = models.CharField(max_length=200, blank=True)
	store_name = models.CharField(max_length=200)
	def __str__(self):
		return self.store_name

class WifiGuestForm(ModelForm):
	store = models.ForeignKey(StoreInfo, on_delete=models.CASCADE)
	class Meta:
		model = WifiGuest
		fields = ['email']
		widgets = {
			'email' : TextInput(attrs={'placeholder': "Enter your email"})
		}

honeypot/views.py
from django.shortcuts import render, get_object_or_404
from .models import StoreInfo, WifiGuestForm

def index(request):
	stores_with_wifi = StoreInfo.objects.all()
	context = {
		'stores_with_wifi': stores_with_wifi,
		}
	return render(request,'honeypot/index.html',context)

def welcome(request, store_id):
	storeWelcome = get_object_or_404(StoreInfo, pk=store_id)
	form = WifiGuestForm()
	context = {
			'store': storeWelcome,
			'form':form
		}
	return render(request, 'honeypot/welcome.html', context)

def thanks(request, store_id):
	submit_email = get_object_or_404(StoreInfo, pk=store_id)
	context = {
		'store':submit_email
	}
	form = WifiGuestForm(request.POST)
	if form.is_valid():
		email_address = form.save(commit=False)
		email_address.post = submit_email
		email_address.save()
		return render(request, 'honeypot/thanks.html', context)
	else:
		return render(request, 'honeypot/thanks.html', context)

honeypot/templates/honeypot/index.html
{% if stores_with_wifi %}
    <ul>
    {% for store in stores_with_wifi %}
        <li><a href="{% url 'honeypot:welcome' store.pk %}">{{ store.store_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No stores are available.</p>
{% endif %}

honeypot/templates/honeypot/thanks.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<div class="floater">
<h1>{{ store.store_name }}</h1>
<hr>
<p>Thanks! You're free to browse the web.</p>
</div>

honeypot/templates/honeypot/welcome.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<div class="floater">
<h1>Welcome to the {{ store.store_name }}</h1>
<hr>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<p>You are welcome to use our wifi while you enjoy your meal. Enter your email for news and offers from {{ store.store_name }}.</p>

<form action="{% url 'honeypot:thanks' store.pk %}" method="POST">
	{% csrf_token %}
	{{ form }}
	<br>
	<input class="sButton" type="submit" value="Accept & Connect">
</form>

<p class="small">I agree to the <a href="link">terms</a> and <a href="link">conditions</a> of service</p>
</div>